const LIMIT_TEMAS  = 5
const LONGITUD_MINIMA_NOMBRE_TEMA = 1
const LONGITUD_MAXIMA_NOMBRE_TEMA = 50

const LIMIT_IDIOMAS = 5
const LONGITUD_MINIMA_NOMBRE_IDIOMA = 1
const LONGITUD_MAXIMA_NOMBRE_IDIOMA = 50

const LIMIT_EDITORIALES = 5
const LONGITUD_MINIMA_NOMBRE_EDITORIAL = 1
const LONGITUD_MAXIMA_NOMBRE_EDITORIAL = 50

const LIMIT_FABRICANTES = 5
const LONGITUD_MINIMA_NOMBRE_FABRICANTE = 1
const LONGITUD_MAXIMA_NOMBRE_FABRICANTE = 50

const LIMIT_LIBROS = 5
const LIMIT_TUTORIALES = 5

module.exports = {
    LIMIT_TEMAS,    
    LONGITUD_MAXIMA_NOMBRE_TEMA,
    LONGITUD_MINIMA_NOMBRE_TEMA,
    LIMIT_IDIOMAS,    
    LONGITUD_MINIMA_NOMBRE_IDIOMA,
    LONGITUD_MAXIMA_NOMBRE_IDIOMA,
    LIMIT_EDITORIALES,    
    LONGITUD_MINIMA_NOMBRE_EDITORIAL,
    LONGITUD_MAXIMA_NOMBRE_EDITORIAL,
    LIMIT_FABRICANTES,    
    LONGITUD_MINIMA_NOMBRE_FABRICANTE,
    LONGITUD_MAXIMA_NOMBRE_FABRICANTE,
    LIMIT_LIBROS,
    LIMIT_TUTORIALES    
}