const LIMIT_TEMAS  = 1000
const OFFSET_TEMAS = 0
const LONGITUD_MINIMA_NOMBRE_TEMA = 1
const LONGITUD_MAXIMA_NOMBRE_TEMA = 50

const LIMIT_IDIOMAS  = 1000
const OFFSET_IDIOMAS = 0
const LONGITUD_MINIMA_NOMBRE_IDIOMA = 1
const LONGITUD_MAXIMA_NOMBRE_IDIOMA = 50

const LIMIT_EDITORIALES  = 1000
const OFFSET_EDITORIALES = 0
const LONGITUD_MINIMA_NOMBRE_EDITORIAL = 1
const LONGITUD_MAXIMA_NOMBRE_EDITORIAL = 50

const LIMIT_FABRICANTES  = 1000
const OFFSET_FABRICANTES = 0
const LONGITUD_MINIMA_NOMBRE_FABRICANTE = 1
const LONGITUD_MAXIMA_NOMBRE_FABRICANTE = 50

const LIMIT_LIBROS  = 1000
const OFFSET_LIBROS = 1

const LIMIT_TUTORIALES  = 1000
const OFFSET_TUTORIALES = 1


module.exports = {
    LIMIT_TEMAS,
    OFFSET_TEMAS,
    LONGITUD_MAXIMA_NOMBRE_TEMA,
    LONGITUD_MINIMA_NOMBRE_TEMA,
    LIMIT_IDIOMAS,
    OFFSET_IDIOMAS,
    LONGITUD_MINIMA_NOMBRE_IDIOMA,
    LONGITUD_MAXIMA_NOMBRE_IDIOMA,
    LIMIT_EDITORIALES,
    OFFSET_EDITORIALES,
    LONGITUD_MINIMA_NOMBRE_EDITORIAL,
    LONGITUD_MAXIMA_NOMBRE_EDITORIAL,
    LIMIT_FABRICANTES,
    OFFSET_FABRICANTES,
    LONGITUD_MINIMA_NOMBRE_FABRICANTE,
    LONGITUD_MAXIMA_NOMBRE_FABRICANTE,
    LIMIT_LIBROS,
    LIMIT_TUTORIALES,
    OFFSET_LIBROS,
    OFFSET_TUTORIALES
}